Add divergence check and max slippage
DistributedCollective/Sovryn-smart-contracts pull request #105
Opened 2021-01-15 03:36 UTC by wukong-xxs

2021-01-29 12:56 UTC, ororopickpocket requested changes
It looks good, Wukong, but we'll need some changes, nonetheless. 

The frontend is preparing a confirmation window where the user can select the maximum slippage he's allowing from the expected price he's being shown. However, this will not be the oracle price (like it is the case now on the trading page), but the expected price from the AMM. This means, a divergence check between AMM and oracle price is not what we need.

What we need instead is to allow the user to pass the minReturn value, similar to how it is on the oracle based amm. In case of the swap, you can simply pass on the value to the AMM contracts. they will handle it automatically. in case of the margin trade it's a bit more complicated. 

one option is to let the user pass the minimum position size in the collateral currency. 

there are certainly other options as well. feel free to propose one if you find another one better suited.

2021-03-16 13:10 UTC, ororopickpocket requested changes

2021-03-16 13:10 UTC, ororopickpocket commented on tests/test_SwapsExternal.py
> +    assert(result > 0)
better would be to check the actual number which is expected

2021-03-16 13:10 UTC, ororopickpocket commented on tests/test_SwapsExternal.py
> +    assert(external_swap['destAmount'] == tx.return_value[0])
better to also check the actual value. it should be the same as the expected one.

2021-03-16 13:10 UTC, ororopickpocket commented on contracts/connectors/loantoken/LoanTokenLogicStandard.sol
> +		require(newCollateral >= minReturn, "new collateral too low");
if you're having the check here, the user has to pay the full amount if gas even if his transaction fails. it's better to have it at the beginning and use the same function as the SwapsExternal (see comments there)

2021-03-16 13:10 UTC, ororopickpocket commented on contracts/modules/SwapsExternal.sol
> +        require(destTokenAmountReceived >= minReturn, "destTokenAmountReceived too low");
you're missing unit tests for this. make a realistic test case, please.

rate on the contract is 1 BTC = 10000 USD
let's assume you do not want to lose more than 2%. Calculate the expected collateral size, pass it to the function and change the rate on the oracle. See if it's behaving as expected.

2021-03-26 10:36 UTC, eMarchenko requested changes
`checkPriceDivergence` and `priceFeeds_` issues probably deserve additional discussion

2021-03-26 10:36 UTC, eMarchenko commented on contracts/connectors/loantoken/LoanTokenLogicDai.sol
> +		uint256 minReturn,
some `tab` issues

2021-03-26 10:36 UTC, eMarchenko commented on contracts/connectors/loantoken/LoanTokenLogicStandard.sol
> +		require(minReturn >= 0, "minReturn must larger than zero");
it is `uint`, it is always greater or equal zero.  most probably, should be `require(minReturn > 0, ...)`

2021-03-26 10:36 UTC, eMarchenko commented on contracts/connectors/loantoken/LoanTokenLogicStandard.sol
> +		if (transactionLimit[collateralTokenAddress] > 0) require(collateralTokenSent <= transactionLimit[collateralTokenAddress]);
`require(transactionLimit[collateralTokenAddress] == 0 || collateralTokenSent <= transactionLimit[collateralTokenAddress]);` is arguably more readable, especially
```ts 
uint limit = transactionLimit[collateralTokenAddress];
require(limit == 0 || collateralTokenSent <= limit);
```

2021-03-26 10:36 UTC, eMarchenko commented on contracts/modules/SwapsExternal.sol
> +        require(minReturn >= 0, "minReturn must larger than zero");
`minReturn > 0`

2021-03-26 10:36 UTC, eMarchenko commented on contracts/modules/SwapsExternal.sol
> +        result = rate == rateFromSwap ? true : false;
just `result = rate == rateFromSwap;`
using `true` and `false` in comparisons and other logical expressions is generally discouraged

2021-03-26 10:36 UTC, eMarchenko commented on contracts/modules/SwapsExternal.sol
> +        address priceFeeds_
why the caller controls `priceFeeds_`? it looks dangerous. Feels like oracle manipulation for free.

2021-03-26 10:36 UTC, eMarchenko commented on contracts/modules/SwapsExternal.sol
> +        address priceFeeds_)
`priceFeeds_` controlled by the caller

2021-06-18 08:20 UTC, jameshowlett977 reviewed
Please add tests for the following functions:
checkPriceDivergence
marginTrade (minReturn/minPoisitonSize > 0)
swapExternal

Passing minReturn/minPoisitonSize = 0 to existing tests is not enough.

2021-06-18 08:20 UTC, jameshowlett977 commented on interfaces/ISovryn.sol
> +contract ISovryn is
Why do we need second ISovryn interface?

2021-07-26 16:15 UTC, korepkorep reviewed
Several code quality issues that don't endanger contracts` security

2021-07-28 10:13 UTC, merged