Change trading rebate rewards SOV become liquid
DistributedCollective/Sovryn-smart-contracts pull request #365
Opened 2021-09-06 16:46 UTC by cwsnt

Enable setter & getter for locked sov basis point
Added Deployment script & unit test for the setter & getter

2021-09-07 07:40 UTC, ororopickpocket requested changes

2021-09-07 07:40 UTC, ororopickpocket commented on contracts/core/State.sol
> +	uint256 internal tradingRebateRewardsBasisPoint;
all variables which are added should be documented.
e.g.: 
Defines the portion of the trading fees which is to be paid out in a liquid form in basis points (0.01%). The rest is vested.

2021-09-07 07:40 UTC, ororopickpocket commented on contracts/modules/ProtocolSettings.sol
> +	function setTradingRebateRewardsBasisPoint(uint256 newBasisPoint) external onlyOwner whenNotPaused {
documentation missing.
never add functions without documentation.

2021-09-07 07:40 UTC, ororopickpocket commented on contracts/modules/ProtocolSettings.sol
> +	function getTradingRebateRewardsBasisPoint() external view returns (uint256) {
same here

2021-09-07 07:40 UTC, ororopickpocket commented on contracts/modules/ProtocolSettings.sol
> +		require(newBasisPoint <= 10000, "value too high");
lockedSOV only allows 9999, does it not? So, we should have the same restriction here.

2021-09-08 12:35 UTC, eMarchenko approved these changes

2021-09-09 07:29 UTC, merged