fix: money lost on extendLoanDuration
DistributedCollective/Sovryn-smart-contracts pull request #425
Opened 2022-03-25 06:39 UTC by cwsnt

when used collateral to extend the loan duration, will use the whole converted loan token instead of the pre-defined input by user.

2022-03-31 21:14 UTC, tjcloa approved these changes

2022-04-06 10:41 UTC, ororopickpocket requested changes
Code change looks good to me, but the formatting not. Is the prettier no longer part of the CI?

2022-04-06 12:08 UTC, cwsnt commented
> Code change looks good to me, but the formatting not. Is the prettier no longer part of the CI?

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/42370767/161970807-60418ad5-6684-4a91-9c61-2d0f705a3dd5.png">

It's still part of the CI.

Also, I have re-run the formatting and seems like no issues. You might need to reinstall the npm package and re-run the formatting?

2022-04-12 14:37 UTC, merged

2022-04-13 07:52 UTC, tjcloa commented
> Code change looks good to me, but the formatting not. Is the prettier no longer part of the CI?

it is
https://github.com/DistributedCollective/Sovryn-smart-contracts/actions/runs/2038500257/workflow#L41

2022-04-13 13:07 UTC, cwsnt commented
Deployment script:
only need to run replaceLoanMaintenance()