Reintroduce governanceWithdraw function
DistributedCollective/Sovryn-smart-contracts pull request #487
Opened 2023-02-15 07:57 UTC by cwsnt

2023-02-21 13:19 UTC, ororopickpocket requested changes

2023-02-22 02:28 UTC, cwsnt commented on contracts/governance/Vesting/fouryear/FourYearVestingLogic.sol
> +                }
updated in this [commit](https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/487/commits/a67d64a582875af2df507533eab1953de0e24818)

2023-02-22 02:28 UTC, cwsnt commented on tests/staking/PauseStaking.test.js
> +        it("governanceWithdrawVesting and cancelTeamVesting function should not be overlapped", async () => {
updated in this [commit](https://github.com/DistributedCollective/Sovryn-smart-contracts/pull/487/commits/a67d64a582875af2df507533eab1953de0e24818)

2023-03-01 12:32 UTC, ororopickpocket approved these changes

2023-03-07 22:46 UTC, tjcloa commented on contracts/governance/Vesting/VestingLogic.sol
> +        require(msg.sender == address(staking), "unauthorized");
missing a warning comment that this function should not be used with sovryn protocol

2023-03-07 22:47 UTC, tjcloa commented on contracts/governance/Staking/interfaces/IStaking.sol
> +    /**
missing a warning comment not to use in sovryn

2023-03-07 22:49 UTC, tjcloa commented on contracts/mockup/modules/IStakingModuleBlockMockup.sol
> +    /**
despite this is a mocking contract it doesn't hurt to add a deprecation warning for sovryn

2023-03-07 22:52 UTC, tjcloa approved these changes
pls add missing deprecation warnings not to use governance vesting withdrawals in the code to avoid confusion in the future - see inline comments

2023-03-08 08:50 UTC, merged